name = "test"
version = "0.1.0"
defaultTargets = ["test"]

[[require]]
name = "batteries"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/batteries"
rev = "main"

[[lean_lib]]
name = "test"
